services:
  frontend:
    image: enerlova-frontend:test
    container_name: enerlova-frontend-test
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://enerlovauat.mmlovalledor.cl/Enerlova
        VITE_APP_ENV: test
    environment:
      - NODE_ENV=production
      - VITE_APP_ENV=test
    networks:
      - proxy
      - enerlova-test
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      
      # Router para frontend
      - "traefik.http.routers.enerlova-frontend-test.rule=Host(`enerlovauat.mmlovalledor.cl`)"
      - "traefik.http.routers.enerlova-frontend-test.entrypoints=websecure"
      - "traefik.http.routers.enerlova-frontend-test.tls=true"
      
      # Servicio
      - "traefik.http.services.enerlova-frontend-test.loadbalancer.server.port=80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  enerlova-test:
    driver: bridge
  proxy:
    external: true