# docker-compose.test.yml - Entorno de Pruebas (Automático)
version: "3.8"

services:
  frontend-test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://enerlovauat.mmlovalledor.cl/Enerlova
        VITE_APP_ENV: uat # Config de UAT
    ports:
      - "32010:80"
    container_name: enerlova-frontend-test
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_APP_ENV=production
    networks:
      - enerlova-network

    # Limitar recursos
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  enerlova-network:
    driver: bridge
