sonar.projectKey=lo-valledor_Frontend_Fi_Agualova_2026
sonar.organization=lo-valledor-1
sonar.host.url=https://sonarcloud.io

sonar.sources=app
sonar.tests=app,test
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/build/**,**/.react-router/**,**/node_modules/**,**/*.d.ts,**/*.config.*
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

