# traefik.yml - Configuración estática para TEST/UAT

api:
  dashboard: true
  insecure: true # Solo para TEST, permite acceso sin autenticación

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        options: default

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: proxy
  file:
    filename: /config.yml
    watch: true

log:
  level: DEBUG # Nivel detallado para TEST

accessLog:
  filePath: '/var/log/traefik/access.log'
  format: json

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
