env:
  contexts:
    - name: "MiContextoWeb"
      urls:
        - "http://172.17.0.1:3000" # URL base para Docker
      includePaths:
        - "http://172.17.0.1:3000.*"
      excludePaths:
        - ".*logout.*"
        - ".*robots\\.txt.*"
      
      # --- CONFIGURACIÓN DE AUTENTICACIÓN ---
      authentication:
        method: "json" # Cambiar a "form" si es un submit clásico
        parameters:
          loginPageUrl: "http://172.17.0.1:3000/login"
          # La estructura del JSON que tu API espera. 
          # {%username%} y {%password%} son variables que inyectaremos.
          loginRequestData: '{"email":"{%username%}","password":"{%password%"}'
        verification:
          method: "response"
          # IMPORTANTE: Algo que solo salga en el HTML/Respuesta cuando entraste
          loggedInRegex: "\QLog Out\E" 
          loggedOutRegex: "\QSign In\E"

      # --- GESTIÓN DE SESIÓN ---
      sessionManagement:
        method: "cookie" # O "header" si usas JWT en Auth Header

      # --- USUARIO ---
      users:
        - name: "zaptester"
          credentials:
            username: "${ZAP_USER}" # Variable de entorno (Secret)
            password: "${ZAP_PASS}" # Variable de entorno (Secret)
  
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true

jobs:
  - type: "spider"
    parameters:
      user: "zaptester" # Le decimos que use el usuario creado arriba
      maxDuration: 2
      
  - type: "spiderAjax" # Vital para tu app Vite/React
    parameters:
      user: "zaptester"
      maxDuration: 5
      
  - type: "activeScan" # El ataque real
    parameters:
      user: "zaptester"
      policy: "Default Policy"
    
  - type: "report"
    parameters:
      template: "traditional-html"
      reportDir: "/zap/wrk/"
      reportFile: "zap-report.html"